"""
Common Terminal UI Module

共享的终端 UI 组件，供 CLI 和 TUI 使用。

🚪 Access - 📦 Common - Terminal UI
"""

__version__ = "0.1.0"

# 导出所有公共组件
from common.terminal.colors import (
    Colors,
    color,
    Theme,
    should_use_color,
    supports_ansi,
    enable_ansi_support,
    strip_color,
    get_terminal_width,
    get_terminal_height,
    HEX_AVOCADO,
    HEX_AVOCADO_BRIGHT,
    HEX_AVOCADO_DIM,
    RGB_AVOCADO,
    RGB_AVOCADO_BRIGHT,
    RGB_AVOCADO_DIM,
    # 便捷函数
    success,
    error,
    warning,
    info,
    accent,
    dim,
    bold,
)

from common.terminal.banner import (
    build_welcome_banner,
    print_simple_banner,
    HAS_RICH,
    AVOCADO,
    AVOCADO_BRIGHT,
    AVOCADO_DIM,
    AVOCADO_DARK,
    WHITE,
    GRAY_DIM,
    GOLD,
)

from common.terminal.output import (
    print_info,
    print_success,
    print_warning,
    print_error,
    print_header,
    print_debug,
    print_divider,
    print_step,
    print_substep,
    print_end_step,
    print_box,
    print_table_row,
    print_spinner,
    Spinner,
    prompt,
    prompt_yes_no,
    prompt_choice,
    print_rich_table,
    print_stream_start,
    print_stream_chunk,
    print_stream_end,
    StreamingPrinter,
)

from common.terminal.ui import (
    print_info as ui_print_info,
    print_success as ui_print_success,
    print_warning as ui_print_warning,
    print_error as ui_print_error,
    print_header as ui_print_header,
    print_divider as ui_print_divider,
    StatusBar,
    status_bar,
    print_banner,
    print_banner_simple,
    print_top_border,
    print_bottom_border,
    print_border_side,
    print_boxed_message,
    print_prompt,
    print_header_text,
    print_menu,
    print_config_item,
    print_list,
    print_agent_response,
    print_status_bar,
    print_user_input,
    print_provider_list,
    print_setup_complete,
    print_rich_table as ui_print_rich_table,
    print_rich_panel,
    print_rich_progress,
    print_rich_success,
    print_rich_error,
    print_rich_warning,
    print_rich_info,
    format_round,
)

from common.terminal.curses_ui import (
    has_curses,
    curses_radiolist,
    curses_checklist,
    radio_select,
    multi_select,
    flush_stdin,
    IS_WINDOWS,
    IS_TTY,
)

__all__ = [
    # Colors
    "Colors",
    "color",
    "Theme",
    "should_use_color",
    "supports_ansi",
    "enable_ansi_support",
    "strip_color",
    "get_terminal_width",
    "get_terminal_height",
    "HEX_AVOCADO",
    "HEX_AVOCADO_BRIGHT",
    "HEX_AVOCADO_DIM",
    "RGB_AVOCADO",
    "RGB_AVOCADO_BRIGHT",
    "RGB_AVOCADO_DIM",
    # 便捷函数
    "success",
    "error",
    "warning",
    "info",
    "accent",
    "dim",
    "bold",
    # Banner
    "build_welcome_banner",
    "print_simple_banner",
    "HAS_RICH",
    "AVOCADO",
    "AVOCADO_BRIGHT",
    "AVOCADO_DIM",
    "AVOCADO_DARK",
    "WHITE",
    "GRAY_DIM",
    "GOLD",
    # Output
    "print_info",
    "print_success",
    "print_warning",
    "print_error",
    "print_header",
    "print_debug",
    "print_divider",
    "print_step",
    "print_substep",
    "print_end_step",
    "print_box",
    "print_table_row",
    "print_spinner",
    "Spinner",
    "prompt",
    "prompt_yes_no",
    "prompt_choice",
    "print_rich_table",
    "print_stream_start",
    "print_stream_chunk",
    "print_stream_end",
    "StreamingPrinter",
    # UI
    "StatusBar",
    "status_bar",
    "print_banner",
    "print_banner_simple",
    "print_top_border",
    "print_bottom_border",
    "print_border_side",
    "print_boxed_message",
    "print_prompt",
    "print_header_text",
    "print_menu",
    "print_config_item",
    "print_list",
    "print_agent_response",
    "print_status_bar",
    "print_user_input",
    "print_provider_list",
    "print_setup_complete",
    "print_rich_table as ui_print_rich_table",
    "print_rich_panel",
    "print_rich_progress",
    "print_rich_success",
    "print_rich_error",
    "print_rich_warning",
    "print_rich_info",
    "format_round",
    # Curses UI
    "has_curses",
    "curses_radiolist",
    "curses_checklist",
    "radio_select",
    "multi_select",
    "flush_stdin",
    "IS_WINDOWS",
    "IS_TTY",
]
