"""
技能合成器
从成功案例中提取可复用的技能
"""

from typing import Dict, Any, List, Optional
from dataclasses import dataclass


@dataclass
class SynthesizedSkill:
    """合成的技能"""
    name: str
    description: str
    trigger_patterns: List[str]
    action_template: str
    confidence: float


class SkillSynthesizer:
    """技能合成器"""
    
    def __init__(self):
        self._patterns: Dict[str, List[str]] = {}
    
    async def synthesize(
        self, 
        trajectory: List[Dict[str, Any]], 
        context: Dict[str, Any] = None
    ) -> Optional[SynthesizedSkill]:
        """
        从轨迹中合成技能
        
        策略：
        1. 分析成功的轨迹
        2. 提取通用的触发模式
        3. 生成可复用的技能模板
        """
        context = context or {}
        
        # 检查轨迹是否适合提取技能
        if not self._is_candidate_for_synthesis(trajectory):
            return None
        
        # 提取触发模式
        trigger_patterns = self._extract_trigger_patterns(trajectory)
        
        # 生成动作模板
        action_template = self._generate_action_template(trajectory)
        
        # 生成技能名称和描述
        name = self._generate_name(trajectory, context)
        description = self._generate_description(trajectory)
        
        # 计算置信度
        confidence = self._calculate_confidence(trajectory)
        
        return SynthesizedSkill(
            name=name,
            description=description,
            trigger_patterns=trigger_patterns,
            action_template=action_template,
            confidence=confidence,
        )
    
    def _is_candidate_for_synthesis(self, trajectory: List[Dict[str, Any]]) -> bool:
        """检查是否适合提取技能"""
        # 需要至少有一定数量的成功步骤
        if len(trajectory) < 3:
            return False
        
        # 检查是否有重复模式
        actions = [s.get("action", "") for s in trajectory]
        return len(set(actions)) > 1  # 有多种不同操作
    
    def _extract_trigger_patterns(self, trajectory: List[Dict[str, Any]]) -> List[str]:
        """提取触发模式"""
        patterns = []
        
        # 从用户输入中提取关键词
        for step in trajectory:
            if step.get("role") == "user":
                content = step.get("content", "")
                # 提取关键词（简化实现）
                words = content.split()[:5]
                patterns.extend([w for w in words if len(w) > 3])
        
        return list(set(patterns))[:10]  # 去重并限制数量
    
    def _generate_action_template(self, trajectory: List[Dict[str, Any]]) -> str:
        """生成动作模板"""
        actions = []
        
        for step in trajectory:
            action = step.get("action", "")
            if action:
                # 简化的模板生成
                actions.append(f"1. {action}")
        
        return "\n".join(actions)
    
    def _generate_name(self, trajectory: List[Dict[str, Any]], context: Dict[str, Any]) -> str:
        """生成技能名称"""
        # 从轨迹中提取主题
        first_user_msg = ""
        for step in trajectory:
            if step.get("role") == "user":
                first_user_msg = step.get("content", "")
                break
        
        # 生成简化的名称
        if first_user_msg:
            return f"AutoGenerated_{first_user_msg[:20]}"
        
        return "AutoGenerated_Skill"
    
    def _generate_description(self, trajectory: List[Dict[str, Any]]) -> str:
        """生成技能描述"""
        actions = [s.get("action", "") for s in trajectory if s.get("action")]
        return f"自动生成的技能，包含 {len(actions)} 个操作步骤"
    
    def _calculate_confidence(self, trajectory: List[Dict[str, Any]]) -> float:
        """计算置信度"""
        # 基于轨迹长度和复杂度计算
        base_confidence = min(len(trajectory) / 10, 0.8)
        return base_confidence